# Nixpacks configuration for Railway deployment
# This file configures how Railway builds and runs the application

[phases.setup]
nixPkgs = ["nodejs", "npm", "caddy"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
    "npm run build:prod",
    "mkdir -p /srv",
    "cp -r dist/brgy-konek-web/* /srv/",
    "cp Caddyfile /srv/",
    "chmod -R 755 /srv"
]

[start]
cmd = "caddy run --config /srv/Caddyfile --adapter caddyfile --port $PORT"
