/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/create-account`; params?: Router.UnknownInputParams; } | { pathname: `/auth/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `/auth/reset-password`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signin`; params?: Router.UnknownInputParams; } | { pathname: `/auth/verify-otp`; params?: Router.UnknownInputParams; } | { pathname: `/user/my-pofile`; params?: Router.UnknownInputParams; } | { pathname: `/user`; params?: Router.UnknownInputParams; } | { pathname: `/user/complaints`; params?: Router.UnknownInputParams; } | { pathname: `/user/announcements`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/create-account`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/forgot-password`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/reset-password`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/signin`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/verify-otp`; params?: Router.UnknownOutputParams; } | { pathname: `/user/my-pofile`; params?: Router.UnknownOutputParams; } | { pathname: `/user`; params?: Router.UnknownOutputParams; } | { pathname: `/user/complaints`; params?: Router.UnknownOutputParams; } | { pathname: `/user/announcements`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/auth/create-account${`?${string}` | `#${string}` | ''}` | `/auth/forgot-password${`?${string}` | `#${string}` | ''}` | `/auth/reset-password${`?${string}` | `#${string}` | ''}` | `/auth/signin${`?${string}` | `#${string}` | ''}` | `/auth/verify-otp${`?${string}` | `#${string}` | ''}` | `/user/my-pofile${`?${string}` | `#${string}` | ''}` | `/user${`?${string}` | `#${string}` | ''}` | `/user/complaints${`?${string}` | `#${string}` | ''}` | `/user/announcements${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/create-account`; params?: Router.UnknownInputParams; } | { pathname: `/auth/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `/auth/reset-password`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signin`; params?: Router.UnknownInputParams; } | { pathname: `/auth/verify-otp`; params?: Router.UnknownInputParams; } | { pathname: `/user/my-pofile`; params?: Router.UnknownInputParams; } | { pathname: `/user`; params?: Router.UnknownInputParams; } | { pathname: `/user/complaints`; params?: Router.UnknownInputParams; } | { pathname: `/user/announcements`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
